### ISSUE TITLE
무중단 배포 구현하기

### ISSUE THREAD

**Issue by hotheadfactory** [woowacourse-teams/2020-saebyeok#217]
### 목적
무중단 배포를 구현하여 배포 중에도 끊김없는 서비스가 가능하도록 한다.

### 체크리스트
- [x] 무중단 배포 컨셉 및 적용 방법 리서치
- [x] 무중단 배포를 구현
  - [x] 현재 동작중인 프로그램 프로필 확인 API 구현
  - [x] 배포 스크립트 수정
  - [x] Nginx 설정 수정
  - [x] 배포 후 Nginx 연결 포트 switching 스크립트 작성

### 일정

**Comment by SujinEmilyCho** [comment]
# 무중단 배포
서비스 중인 프로그램을 새로 배포할 때 서비스가 중단되지 않게 배포하는 기술

# Nginx와 AWS EC2 서버 1개를 이용한 블루 그린 배포 과정
![image](https://user-images.githubusercontent.com/49009406/97985423-96ed0c80-1e1b-11eb-90b2-1648bf4869b3.png)

1. Jenkins 서버에 Webhook으로 빌드 시작
2. 빌드 후, EC2서버에 .jar 파일을 전달하고 배포 스크립트 실행
3. 현재 서비스 중인 서버의 프로필을 확인
4. 타겟(쉬고 있는) 프로필 정의
5. 타겟에 해당하는 포트가 실행중이면 프로세스 kill
6. 타겟 프로필로 애플리케이션 배포
7. Nginx가 연결하는 포트 번호 스위칭

# 참고 자료
### 무중단 배포 종류
1. 블루 그린 배포
![image](https://user-images.githubusercontent.com/49009406/97984123-a9fedd00-1e19-11eb-9e3b-3ceff99c1cca.png)
2. [롤링 업데이트](https://ooeunz.tistory.com/124)
![image](https://user-images.githubusercontent.com/49009406/97984107-a5d2bf80-1e19-11eb-86d0-d0a29c0044e6.png)
3. [카나리 배포](https://jason-lim.tistory.com/3)
![image](https://user-images.githubusercontent.com/49009406/97984160-b4b97200-1e19-11eb-9abd-c8a17a9dae44.png)

### 참고 링크
[무중단 배포 종류](https://onlywis.tistory.com/10)
[Nginx를 이용한 무중단 배포 방법](https://jojoldu.tistory.com/267)
