### ISSUE TITLE
회의록 업로드하기

### ISSUE THREAD

**Issue by icyMojito** [woowacourse-teams/2020-saebyeok#22]
### 목적

서비스와 관련된 회의 내용을 정리하고 기록하여 프로젝트 진행 시 참고할 수 있다. 

### 체크리스트

- [x]  기획 단계에서 진행했던 회의를 회의록 템플릿에 맞게 정리하기
- [x]  깃허브 위키에 업로드하기

### 주의 사항

- 차후 회의에서는 1시간 이내에 깃허브 위키에 회의록을 업로드하기

### 관련 이슈

- 회의록 템플릿 협의하고 작성하기(#19)

### 일정

- 스프린트1

**Comment by SujinEmilyCho** [comment]
완료😉
