### ISSUE TITLE
코드 품질 개선을 위한 SonarQube, Jacoco 적용

### ISSUE THREAD

**Issue by include42** [woowacourse-teams/2020-saebyeok#245]
### 목적
SonarQube와 Jacoco를 프로젝트에 추가하여, 코드 품질을 관리한다.

### 체크리스트
- [x] EC2에 SonarQube 서버 인프라 구축
- [x] Jenkins에 SonarQube 플러그인 연결
- [x] 프로젝트 Gradle에 Jacoco 추가
- [x] Jenkins에서 SonarQube Fail 나오는 문제 해결하기

### 주의 사항
현재는 Jacoco의 Coverage Limit이 0%로 설정되어 있다. 그러나 추후 80%까지 올릴 예정이다.
Jacoco 테스트 도중 Lombok으로 인한 Coverage 감소 이슈가 있었다. [링크](https://velog.io/@dahye4321/스프링-가이드-2#가능하다면-lombokconfig-설정을-통해-제한하자)

도움을 받은 문서
- https://beomseok95.tistory.com/201?category=1054282
- https://www.notion.so/sonarqube-dddacb2c16d945e8a4ff2fd1978f781a

### 관련 이슈
- 
### 일정
-

**Comment by hotheadfactory** [comment]
SonarQube 정상 작동 확인했습니다 :)
