### ISSUE TITLE
간단한 글 작성 기능 구현하기

### ISSUE THREAD

**Issue by hotheadfactory** [woowacourse-teams/2020-saebyeok#35]
### 목적
우선 간단한 글 작성 기능을 구현해 보기
### 체크리스트
- [x] Article 인수 테스트 작성하기
- [x] Article 단위 테스트 작성하기
- [x] ArticleController, ArticleService 구현하기
- [x] 클라이언트에서 전달받은 글 정보를 DB에 저장하는 기능 구현하기
### 관련 이슈
- 
### 일정
- 스프린트 2

**Comment by SujinEmilyCho** [comment]
<글 작성 기능 구현 현황>
- Article 엔티티에 Emotion은 String, Comments는 null로 구현했음
- 회원 관리 기능이 구현되기 전이기 때문에 ArticleService에서 Member를 수동으로 생성해서 주입함

<추후 보강해야할 내용>
- 회원 관리 기능이 구현되면 Article 삭제 할 때 자신의 게시물만 삭제할 수 있도록 코드 추가할 것
